/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CalculatorComponent {
        "calculatorButtons": string[];
    }
}
declare global {
    interface HTMLCalculatorComponentElement extends Components.CalculatorComponent, HTMLStencilElement {
    }
    var HTMLCalculatorComponentElement: {
        prototype: HTMLCalculatorComponentElement;
        new (): HTMLCalculatorComponentElement;
    };
    interface HTMLElementTagNameMap {
        "calculator-component": HTMLCalculatorComponentElement;
    }
}
declare namespace LocalJSX {
    interface CalculatorComponent {
        "calculatorButtons"?: string[];
    }
    interface IntrinsicElements {
        "calculator-component": CalculatorComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "calculator-component": LocalJSX.CalculatorComponent & JSXBase.HTMLAttributes<HTMLCalculatorComponentElement>;
        }
    }
}
