/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CalculatorButton {
        "handleClick": () => void;
        "label": string;
        "widthAuto": boolean;
    }
    interface CalculatorComponent {
        "calculatorButtons": string[];
    }
    interface CalculatorHistory {
        "entries": string[];
    }
}
declare global {
    interface HTMLCalculatorButtonElement extends Components.CalculatorButton, HTMLStencilElement {
    }
    var HTMLCalculatorButtonElement: {
        prototype: HTMLCalculatorButtonElement;
        new (): HTMLCalculatorButtonElement;
    };
    interface HTMLCalculatorComponentElement extends Components.CalculatorComponent, HTMLStencilElement {
    }
    var HTMLCalculatorComponentElement: {
        prototype: HTMLCalculatorComponentElement;
        new (): HTMLCalculatorComponentElement;
    };
    interface HTMLCalculatorHistoryElement extends Components.CalculatorHistory, HTMLStencilElement {
    }
    var HTMLCalculatorHistoryElement: {
        prototype: HTMLCalculatorHistoryElement;
        new (): HTMLCalculatorHistoryElement;
    };
    interface HTMLElementTagNameMap {
        "calculator-button": HTMLCalculatorButtonElement;
        "calculator-component": HTMLCalculatorComponentElement;
        "calculator-history": HTMLCalculatorHistoryElement;
    }
}
declare namespace LocalJSX {
    interface CalculatorButton {
        "handleClick"?: () => void;
        "label"?: string;
        "widthAuto"?: boolean;
    }
    interface CalculatorComponent {
        "calculatorButtons"?: string[];
    }
    interface CalculatorHistory {
        "entries"?: string[];
    }
    interface IntrinsicElements {
        "calculator-button": CalculatorButton;
        "calculator-component": CalculatorComponent;
        "calculator-history": CalculatorHistory;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "calculator-button": LocalJSX.CalculatorButton & JSXBase.HTMLAttributes<HTMLCalculatorButtonElement>;
            "calculator-component": LocalJSX.CalculatorComponent & JSXBase.HTMLAttributes<HTMLCalculatorComponentElement>;
            "calculator-history": LocalJSX.CalculatorHistory & JSXBase.HTMLAttributes<HTMLCalculatorHistoryElement>;
        }
    }
}
